global:
  resolve_timeout: 5m

route:
  receiver: lab-mailpit
  group_by:
    - alertname
    - job
    - instance
    - service
    - check
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: lab-mailpit
    email_configs:
      - to: operator@tomcat-monitoring.invalid
        from: alertmanager@tomcat-monitoring.invalid
        smarthost: mailpit:1025
        require_tls: false
        send_resolved: true
        headers:
          Subject: '[Tomcat Monitoring][{{ .Status }}] {{ .CommonLabels.alertname }} - {{ .CommonLabels.instance }}'
