---
# Main entrypoint for role_host_prep
# Architecture Reference: TM-ADR-0025, TM-ADR-0028, TN-014, TN-018, TN-019

- name: Execute Linux Host Preparation Tasks
  ansible.builtin.include_tasks: linux/main.yml
  when: ansible_os_family != "Windows"

- name: Execute Windows Host Preparation Tasks
  ansible.builtin.include_tasks: windows/main.yml
  when: ansible_os_family == "Windows"
