---
# Main entrypoint for role_event_collector
# Architecture Reference: TM-ADR-0027, TN-013, TN-014, TN-018, TN-019

- name: Execute Linux Event Collector Deployment
  ansible.builtin.include_tasks: linux/main.yml
  when: ansible_os_family != "Windows"

- name: Execute Windows Event Collector Deployment
  ansible.builtin.include_tasks: windows/main.yml
  when: ansible_os_family == "Windows"
