---
# Main entrypoint for role_container_stack
# Architecture Reference: TM-ADR-0025, TM-ADR-0026, TN-014, TN-018, TN-019

- name: Execute Linux Container Stack Deployment
  ansible.builtin.include_tasks: linux/main.yml
  when: ansible_os_family != "Windows"

- name: Execute Windows Container Stack Deployment
  ansible.builtin.include_tasks: windows/main.yml
  when: ansible_os_family == "Windows"
